from PySide6.QtCore import QSize

INPUT_DATA_PATH = 'data'
OUT_DATA_PATH = 'out'

TRACKER_TYPES = ['BOOSTING', 'MIL', 'TLD', 'MEDIANFLOW', 'GOTURN', 'MOSSE', 'CSRT']

IMG_SIZE = (640, 480)

DEFAULT_FRAME_FREQUENCY = 1
DEFAULT_THICKNESS = 4
DEFAULT_SKEW_EFFECT = 15

MAIN_WINDOW_TITLE = 'TubeMapping'
MAIN_WINDOW_MINIMUM_SIZE = QSize(800, 800)

DEFAULT_MAP_SIZE = QSize(600, 1400)
